package movies.tests;

import org.junit.jupiter.api.Test;
import movies.importer.KaggleImporter;
import movies.importer.ValidatorKaggle;

import static org.junit.Assert.assertEquals;

import java.util.*;

/**
 * All tests for anything kaggle related
 * @author Trevor McCubbin
 *
 */
class KaggleTests {
	
	/**
	 * Creates an ArrayList<String> and uses that as an input into the process of kaggle importer
	 * to test the kaggle importer and it's output value
	 */
	@Test
	void testImporterProcess() {
		ArrayList<String> input = new ArrayList<String>();
		input.add("Cast 1\tCast 2\tCast 3\tCast 4\tCast 5\tCast 6\tDescription\tDirector 1\tDirector 2\tDirector 3\tGenre\tRating\tRelease Date\tRuntime\tStudio\tTitle\tWriter 1\tWriter 2\tWriter 3\tWriter 4\tYear\r\n");
		input.add("Brendan Fraser\tJohn Hannah\tMaria Bello\tMichelle Yeoh\tJet Li\tRussell Wong\t\"The Fast and the Furious director Rob Cohen continues the tale set into motion by director Stephen Sommers with this globe-trotting adventure that finds explorer Rick O'Connell and son attempting to thwart a resurrected emperor's (Jet Li) plan to enslave the entire human race. It's been 2,000 years since China's merciless Emperor Han and his formidable army were entombed in terra cotta clay by a double-dealing sorceress (Michelle Yeoh), but now, after centuries in suspended animation, an ancient curse is about to be broken. Thanks to his childhood adventures alongside father Rick (Brendan Fraser) and mother Evelyn (Maria Bello), dashing young archeologist Alex O'Connell (Luke Ford) is more than familiar with the power of the supernatural. After he is tricked into awakening the dreaded emperor from his eternal slumber, however, the frightened young adventurer is forced to seek out the wisdom of his parents -- both of whom have had their fair share of experience battling the legions of the undead. Should the fierce monarch prove capable of awakening his powerful terra cotta army, his diabolical plan for world domination will finally be set into motion. Of course, the one factor that this emperor mummy failed to consider while solidifying his power-mad plans was the O'Connells, and before this battle is over, the monstrous monarch will be forced to contend with the one family that isn't frightened by a few rickety reanimated corpses. ~ Jason Buchanan, Rovi\"\tRob Cohen\tSimon Duggan\tDirector Not Available\tAction\tPG-13\t7/24/2008\t112 minutes\tUniversal Pictures\tThe Mummy: Tomb of the Dragon Emperor\tAlfred Gough\tMiles Millar\tWriter Not Available\tWriter Not Available\t2008");
		ArrayList<String> output = new ArrayList<String>();
		KaggleImporter k = new KaggleImporter("hello", "hey");
		output = k.process(input);
		assertEquals("2008	The Mummy: Tomb of the Dragon Emperor	112 minutes	kaggle", output.get(1));
	}
	
	/**
	 * Creates an ArrayList<String> and tests adding and removing elements from an ArrayList<String>
	 * works properly by comparing it it's size.
	 */
	@Test
	void testImporterCorrectAmountOfAddedLines() {
		// this part should add a header and 2 lines to the output ArrayList
		ArrayList<String> input = new ArrayList<String>();
		input.add("Cast 1\tCast 2\tCast 3\tCast 4\tCast 5\tCast 6\tDescription\tDirector 1\tDirector 2\tDirector 3\tGenre\tRating\tRelease Date\tRuntime\tStudio\tTitle\tWriter 1\tWriter 2\tWriter 3\tWriter 4\tYear\r\n");
		input.add("Brendan Fraser\tJohn Hannah\tMaria Bello\tMichelle Yeoh\tJet Li\tRussell Wong\t\"The Fast and the Furious director Rob Cohen continues the tale set into motion by director Stephen Sommers with this globe-trotting adventure that finds explorer Rick O'Connell and son attempting to thwart a resurrected emperor's (Jet Li) plan to enslave the entire human race. It's been 2,000 years since China's merciless Emperor Han and his formidable army were entombed in terra cotta clay by a double-dealing sorceress (Michelle Yeoh), but now, after centuries in suspended animation, an ancient curse is about to be broken. Thanks to his childhood adventures alongside father Rick (Brendan Fraser) and mother Evelyn (Maria Bello), dashing young archeologist Alex O'Connell (Luke Ford) is more than familiar with the power of the supernatural. After he is tricked into awakening the dreaded emperor from his eternal slumber, however, the frightened young adventurer is forced to seek out the wisdom of his parents -- both of whom have had their fair share of experience battling the legions of the undead. Should the fierce monarch prove capable of awakening his powerful terra cotta army, his diabolical plan for world domination will finally be set into motion. Of course, the one factor that this emperor mummy failed to consider while solidifying his power-mad plans was the O'Connells, and before this battle is over, the monstrous monarch will be forced to contend with the one family that isn't frightened by a few rickety reanimated corpses. ~ Jason Buchanan, Rovi\"\tRob Cohen\tSimon Duggan\tDirector Not Available\tAction\tPG-13\t7/24/2008\t112 minutes\tUniversal Pictures\tThe Mummy: Tomb of the Dragon Emperor\tAlfred Gough\tMiles Millar\tWriter Not Available\tWriter Not Available\t2008");
		input.add("Brendan Fraser\tJohn Hannah\tMaria Bello\tMichelle Yeoh\tJet Li\tRussell Wong\t\"The Fast and the Furious director Rob Cohen continues the tale set into motion by director Stephen Sommers with this globe-trotting adventure that finds explorer Rick O'Connell and son attempting to thwart a resurrected emperor's (Jet Li) plan to enslave the entire human race. It's been 2,000 years since China's merciless Emperor Han and his formidable army were entombed in terra cotta clay by a double-dealing sorceress (Michelle Yeoh), but now, after centuries in suspended animation, an ancient curse is about to be broken. Thanks to his childhood adventures alongside father Rick (Brendan Fraser) and mother Evelyn (Maria Bello), dashing young archeologist Alex O'Connell (Luke Ford) is more than familiar with the power of the supernatural. After he is tricked into awakening the dreaded emperor from his eternal slumber, however, the frightened young adventurer is forced to seek out the wisdom of his parents -- both of whom have had their fair share of experience battling the legions of the undead. Should the fierce monarch prove capable of awakening his powerful terra cotta army, his diabolical plan for world domination will finally be set into motion. Of course, the one factor that this emperor mummy failed to consider while solidifying his power-mad plans was the O'Connells, and before this battle is over, the monstrous monarch will be forced to contend with the one family that isn't frightened by a few rickety reanimated corpses. ~ Jason Buchanan, Rovi\"\tRob Cohen\tSimon Duggan\tDirector Not Available\tAction\tPG-13\t7/24/2008\t112 minutes\tUniversal Pictures\tThe Mummy: Tomb of the Dragon Emperor\tAlfred Gough\tMiles Millar\tWriter Not Available\tWriter Not Available\t2008");
		ArrayList<String> output = new ArrayList<String>();
		KaggleImporter k = new KaggleImporter("hello", "hey");
		output = k.process(input);
		assertEquals(3, output.size());
		// this part should add 9 more lines to the output ArrayList
		input.add("Brendan Fraser\tJohn Hannah\tMaria Bello\tMichelle Yeoh\tJet Li\tRussell Wong\t\"The Fast and the Furious director Rob Cohen continues the tale set into motion by director Stephen Sommers with this globe-trotting adventure that finds explorer Rick O'Connell and son attempting to thwart a resurrected emperor's (Jet Li) plan to enslave the entire human race. It's been 2,000 years since China's merciless Emperor Han and his formidable army were entombed in terra cotta clay by a double-dealing sorceress (Michelle Yeoh), but now, after centuries in suspended animation, an ancient curse is about to be broken. Thanks to his childhood adventures alongside father Rick (Brendan Fraser) and mother Evelyn (Maria Bello), dashing young archeologist Alex O'Connell (Luke Ford) is more than familiar with the power of the supernatural. After he is tricked into awakening the dreaded emperor from his eternal slumber, however, the frightened young adventurer is forced to seek out the wisdom of his parents -- both of whom have had their fair share of experience battling the legions of the undead. Should the fierce monarch prove capable of awakening his powerful terra cotta army, his diabolical plan for world domination will finally be set into motion. Of course, the one factor that this emperor mummy failed to consider while solidifying his power-mad plans was the O'Connells, and before this battle is over, the monstrous monarch will be forced to contend with the one family that isn't frightened by a few rickety reanimated corpses. ~ Jason Buchanan, Rovi\"\tRob Cohen\tSimon Duggan\tDirector Not Available\tAction\tPG-13\t7/24/2008\t112 minutes\tUniversal Pictures\tThe Mummy: Tomb of the Dragon Emperor\tAlfred Gough\tMiles Millar\tWriter Not Available\tWriter Not Available\t2008");
		input.add("Brendan Fraser\tJohn Hannah\tMaria Bello\tMichelle Yeoh\tJet Li\tRussell Wong\t\"The Fast and the Furious director Rob Cohen continues the tale set into motion by director Stephen Sommers with this globe-trotting adventure that finds explorer Rick O'Connell and son attempting to thwart a resurrected emperor's (Jet Li) plan to enslave the entire human race. It's been 2,000 years since China's merciless Emperor Han and his formidable army were entombed in terra cotta clay by a double-dealing sorceress (Michelle Yeoh), but now, after centuries in suspended animation, an ancient curse is about to be broken. Thanks to his childhood adventures alongside father Rick (Brendan Fraser) and mother Evelyn (Maria Bello), dashing young archeologist Alex O'Connell (Luke Ford) is more than familiar with the power of the supernatural. After he is tricked into awakening the dreaded emperor from his eternal slumber, however, the frightened young adventurer is forced to seek out the wisdom of his parents -- both of whom have had their fair share of experience battling the legions of the undead. Should the fierce monarch prove capable of awakening his powerful terra cotta army, his diabolical plan for world domination will finally be set into motion. Of course, the one factor that this emperor mummy failed to consider while solidifying his power-mad plans was the O'Connells, and before this battle is over, the monstrous monarch will be forced to contend with the one family that isn't frightened by a few rickety reanimated corpses. ~ Jason Buchanan, Rovi\"\tRob Cohen\tSimon Duggan\tDirector Not Available\tAction\tPG-13\t7/24/2008\t112 minutes\tUniversal Pictures\tThe Mummy: Tomb of the Dragon Emperor\tAlfred Gough\tMiles Millar\tWriter Not Available\tWriter Not Available\t2008");
		input.add("Brendan Fraser\tJohn Hannah\tMaria Bello\tMichelle Yeoh\tJet Li\tRussell Wong\t\"The Fast and the Furious director Rob Cohen continues the tale set into motion by director Stephen Sommers with this globe-trotting adventure that finds explorer Rick O'Connell and son attempting to thwart a resurrected emperor's (Jet Li) plan to enslave the entire human race. It's been 2,000 years since China's merciless Emperor Han and his formidable army were entombed in terra cotta clay by a double-dealing sorceress (Michelle Yeoh), but now, after centuries in suspended animation, an ancient curse is about to be broken. Thanks to his childhood adventures alongside father Rick (Brendan Fraser) and mother Evelyn (Maria Bello), dashing young archeologist Alex O'Connell (Luke Ford) is more than familiar with the power of the supernatural. After he is tricked into awakening the dreaded emperor from his eternal slumber, however, the frightened young adventurer is forced to seek out the wisdom of his parents -- both of whom have had their fair share of experience battling the legions of the undead. Should the fierce monarch prove capable of awakening his powerful terra cotta army, his diabolical plan for world domination will finally be set into motion. Of course, the one factor that this emperor mummy failed to consider while solidifying his power-mad plans was the O'Connells, and before this battle is over, the monstrous monarch will be forced to contend with the one family that isn't frightened by a few rickety reanimated corpses. ~ Jason Buchanan, Rovi\"\tRob Cohen\tSimon Duggan\tDirector Not Available\tAction\tPG-13\t7/24/2008\t112 minutes\tUniversal Pictures\tThe Mummy: Tomb of the Dragon Emperor\tAlfred Gough\tMiles Millar\tWriter Not Available\tWriter Not Available\t2008");
		input.add("Brendan Fraser\tJohn Hannah\tMaria Bello\tMichelle Yeoh\tJet Li\tRussell Wong\t\"The Fast and the Furious director Rob Cohen continues the tale set into motion by director Stephen Sommers with this globe-trotting adventure that finds explorer Rick O'Connell and son attempting to thwart a resurrected emperor's (Jet Li) plan to enslave the entire human race. It's been 2,000 years since China's merciless Emperor Han and his formidable army were entombed in terra cotta clay by a double-dealing sorceress (Michelle Yeoh), but now, after centuries in suspended animation, an ancient curse is about to be broken. Thanks to his childhood adventures alongside father Rick (Brendan Fraser) and mother Evelyn (Maria Bello), dashing young archeologist Alex O'Connell (Luke Ford) is more than familiar with the power of the supernatural. After he is tricked into awakening the dreaded emperor from his eternal slumber, however, the frightened young adventurer is forced to seek out the wisdom of his parents -- both of whom have had their fair share of experience battling the legions of the undead. Should the fierce monarch prove capable of awakening his powerful terra cotta army, his diabolical plan for world domination will finally be set into motion. Of course, the one factor that this emperor mummy failed to consider while solidifying his power-mad plans was the O'Connells, and before this battle is over, the monstrous monarch will be forced to contend with the one family that isn't frightened by a few rickety reanimated corpses. ~ Jason Buchanan, Rovi\"\tRob Cohen\tSimon Duggan\tDirector Not Available\tAction\tPG-13\t7/24/2008\t112 minutes\tUniversal Pictures\tThe Mummy: Tomb of the Dragon Emperor\tAlfred Gough\tMiles Millar\tWriter Not Available\tWriter Not Available\t2008");
		input.add("Brendan Fraser\tJohn Hannah\tMaria Bello\tMichelle Yeoh\tJet Li\tRussell Wong\t\"The Fast and the Furious director Rob Cohen continues the tale set into motion by director Stephen Sommers with this globe-trotting adventure that finds explorer Rick O'Connell and son attempting to thwart a resurrected emperor's (Jet Li) plan to enslave the entire human race. It's been 2,000 years since China's merciless Emperor Han and his formidable army were entombed in terra cotta clay by a double-dealing sorceress (Michelle Yeoh), but now, after centuries in suspended animation, an ancient curse is about to be broken. Thanks to his childhood adventures alongside father Rick (Brendan Fraser) and mother Evelyn (Maria Bello), dashing young archeologist Alex O'Connell (Luke Ford) is more than familiar with the power of the supernatural. After he is tricked into awakening the dreaded emperor from his eternal slumber, however, the frightened young adventurer is forced to seek out the wisdom of his parents -- both of whom have had their fair share of experience battling the legions of the undead. Should the fierce monarch prove capable of awakening his powerful terra cotta army, his diabolical plan for world domination will finally be set into motion. Of course, the one factor that this emperor mummy failed to consider while solidifying his power-mad plans was the O'Connells, and before this battle is over, the monstrous monarch will be forced to contend with the one family that isn't frightened by a few rickety reanimated corpses. ~ Jason Buchanan, Rovi\"\tRob Cohen\tSimon Duggan\tDirector Not Available\tAction\tPG-13\t7/24/2008\t112 minutes\tUniversal Pictures\tThe Mummy: Tomb of the Dragon Emperor\tAlfred Gough\tMiles Millar\tWriter Not Available\tWriter Not Available\t2008");
		input.add("Brendan Fraser\tJohn Hannah\tMaria Bello\tMichelle Yeoh\tJet Li\tRussell Wong\t\"The Fast and the Furious director Rob Cohen continues the tale set into motion by director Stephen Sommers with this globe-trotting adventure that finds explorer Rick O'Connell and son attempting to thwart a resurrected emperor's (Jet Li) plan to enslave the entire human race. It's been 2,000 years since China's merciless Emperor Han and his formidable army were entombed in terra cotta clay by a double-dealing sorceress (Michelle Yeoh), but now, after centuries in suspended animation, an ancient curse is about to be broken. Thanks to his childhood adventures alongside father Rick (Brendan Fraser) and mother Evelyn (Maria Bello), dashing young archeologist Alex O'Connell (Luke Ford) is more than familiar with the power of the supernatural. After he is tricked into awakening the dreaded emperor from his eternal slumber, however, the frightened young adventurer is forced to seek out the wisdom of his parents -- both of whom have had their fair share of experience battling the legions of the undead. Should the fierce monarch prove capable of awakening his powerful terra cotta army, his diabolical plan for world domination will finally be set into motion. Of course, the one factor that this emperor mummy failed to consider while solidifying his power-mad plans was the O'Connells, and before this battle is over, the monstrous monarch will be forced to contend with the one family that isn't frightened by a few rickety reanimated corpses. ~ Jason Buchanan, Rovi\"\tRob Cohen\tSimon Duggan\tDirector Not Available\tAction\tPG-13\t7/24/2008\t112 minutes\tUniversal Pictures\tThe Mummy: Tomb of the Dragon Emperor\tAlfred Gough\tMiles Millar\tWriter Not Available\tWriter Not Available\t2008");
		input.add("Brendan Fraser\tJohn Hannah\tMaria Bello\tMichelle Yeoh\tJet Li\tRussell Wong\t\"The Fast and the Furious director Rob Cohen continues the tale set into motion by director Stephen Sommers with this globe-trotting adventure that finds explorer Rick O'Connell and son attempting to thwart a resurrected emperor's (Jet Li) plan to enslave the entire human race. It's been 2,000 years since China's merciless Emperor Han and his formidable army were entombed in terra cotta clay by a double-dealing sorceress (Michelle Yeoh), but now, after centuries in suspended animation, an ancient curse is about to be broken. Thanks to his childhood adventures alongside father Rick (Brendan Fraser) and mother Evelyn (Maria Bello), dashing young archeologist Alex O'Connell (Luke Ford) is more than familiar with the power of the supernatural. After he is tricked into awakening the dreaded emperor from his eternal slumber, however, the frightened young adventurer is forced to seek out the wisdom of his parents -- both of whom have had their fair share of experience battling the legions of the undead. Should the fierce monarch prove capable of awakening his powerful terra cotta army, his diabolical plan for world domination will finally be set into motion. Of course, the one factor that this emperor mummy failed to consider while solidifying his power-mad plans was the O'Connells, and before this battle is over, the monstrous monarch will be forced to contend with the one family that isn't frightened by a few rickety reanimated corpses. ~ Jason Buchanan, Rovi\"\tRob Cohen\tSimon Duggan\tDirector Not Available\tAction\tPG-13\t7/24/2008\t112 minutes\tUniversal Pictures\tThe Mummy: Tomb of the Dragon Emperor\tAlfred Gough\tMiles Millar\tWriter Not Available\tWriter Not Available\t2008");
		input.add("Brendan Fraser\tJohn Hannah\tMaria Bello\tMichelle Yeoh\tJet Li\tRussell Wong\t\"The Fast and the Furious director Rob Cohen continues the tale set into motion by director Stephen Sommers with this globe-trotting adventure that finds explorer Rick O'Connell and son attempting to thwart a resurrected emperor's (Jet Li) plan to enslave the entire human race. It's been 2,000 years since China's merciless Emperor Han and his formidable army were entombed in terra cotta clay by a double-dealing sorceress (Michelle Yeoh), but now, after centuries in suspended animation, an ancient curse is about to be broken. Thanks to his childhood adventures alongside father Rick (Brendan Fraser) and mother Evelyn (Maria Bello), dashing young archeologist Alex O'Connell (Luke Ford) is more than familiar with the power of the supernatural. After he is tricked into awakening the dreaded emperor from his eternal slumber, however, the frightened young adventurer is forced to seek out the wisdom of his parents -- both of whom have had their fair share of experience battling the legions of the undead. Should the fierce monarch prove capable of awakening his powerful terra cotta army, his diabolical plan for world domination will finally be set into motion. Of course, the one factor that this emperor mummy failed to consider while solidifying his power-mad plans was the O'Connells, and before this battle is over, the monstrous monarch will be forced to contend with the one family that isn't frightened by a few rickety reanimated corpses. ~ Jason Buchanan, Rovi\"\tRob Cohen\tSimon Duggan\tDirector Not Available\tAction\tPG-13\t7/24/2008\t112 minutes\tUniversal Pictures\tThe Mummy: Tomb of the Dragon Emperor\tAlfred Gough\tMiles Millar\tWriter Not Available\tWriter Not Available\t2008");
		input.add("Brendan Fraser\tJohn Hannah\tMaria Bello\tMichelle Yeoh\tJet Li\tRussell Wong\t\"The Fast and the Furious director Rob Cohen continues the tale set into motion by director Stephen Sommers with this globe-trotting adventure that finds explorer Rick O'Connell and son attempting to thwart a resurrected emperor's (Jet Li) plan to enslave the entire human race. It's been 2,000 years since China's merciless Emperor Han and his formidable army were entombed in terra cotta clay by a double-dealing sorceress (Michelle Yeoh), but now, after centuries in suspended animation, an ancient curse is about to be broken. Thanks to his childhood adventures alongside father Rick (Brendan Fraser) and mother Evelyn (Maria Bello), dashing young archeologist Alex O'Connell (Luke Ford) is more than familiar with the power of the supernatural. After he is tricked into awakening the dreaded emperor from his eternal slumber, however, the frightened young adventurer is forced to seek out the wisdom of his parents -- both of whom have had their fair share of experience battling the legions of the undead. Should the fierce monarch prove capable of awakening his powerful terra cotta army, his diabolical plan for world domination will finally be set into motion. Of course, the one factor that this emperor mummy failed to consider while solidifying his power-mad plans was the O'Connells, and before this battle is over, the monstrous monarch will be forced to contend with the one family that isn't frightened by a few rickety reanimated corpses. ~ Jason Buchanan, Rovi\"\tRob Cohen\tSimon Duggan\tDirector Not Available\tAction\tPG-13\t7/24/2008\t112 minutes\tUniversal Pictures\tThe Mummy: Tomb of the Dragon Emperor\tAlfred Gough\tMiles Millar\tWriter Not Available\tWriter Not Available\t2008");
		output = k.process(input);
		assertEquals(12, output.size());
		input.remove(6);
		output = k.process(input);
		assertEquals(11, output.size());
	}
	
	/**
	 * Creates an ArrayList<String> and tests if the program ignores lines that
	 * don't have enough columns in them.
	 */
	@Test
	void testImporterExceptionNotEnoughColumns() {
		ArrayList<String> input = new ArrayList<String>();
		input.add("Cast 1\tCast 2\tCast 3\tCast 4\tCast 5\tCast 6\tDescription\tDirector 1\tDirector 2\tDirector 3\tGenre\tRating\tRelease Date\tRuntime\tStudio\tTitle\tWriter 1\tWriter 2\tWriter 3\tWriter 4\tYear\r\n");
		input.add("Brendan Fraser\tJohn Hannah\tMaria Bello\tMichelle Yeoh\tJet Li\tRussell Wong\t\"The Fast and the Furious director Rob Cohen continues the tale set into motion by director Stephen Sommers with this globe-trotting adventure that finds explorer Rick O'Connell and son attempting to thwart a resurrected emperor's (Jet Li) plan to enslave the entire human race. It's been 2,000 years since China's merciless Emperor Han and his formidable army were entombed in terra cotta clay by a double-dealing sorceress (Michelle Yeoh), but now, after centuries in suspended animation, an ancient curse is about to be broken. Thanks to his childhood adventures alongside father Rick (Brendan Fraser) and mother Evelyn (Maria Bello), dashing young archeologist Alex O'Connell (Luke Ford) is more than familiar with the power of the supernatural. After he is tricked into awakening the dreaded emperor from his eternal slumber, however, the frightened young adventurer is forced to seek out the wisdom of his parents -- both of whom have had their fair share of experience battling the legions of the undead. Should the fierce monarch prove capable of awakening his powerful terra cotta army, his diabolical plan for world domination will finally be set into motion. Of course, the one factor that this emperor mummy failed to consider while solidifying his power-mad plans was the O'Connells, and before this battle is over, the monstrous monarch will be forced to contend with the one family that isn't frightened by a few rickety reanimated corpses. ~ Jason Buchanan, Rovi\"\tRob Cohen\tSimon Duggan\tDirector Not Available\tAction\tPG-13\t7/24/2008\t112 minutes\tUniversal Pictures\tThe Mummy: Tomb of the Dragon Emperor\tAlfred Gough\tMiles Millar\tWriter Not Available\tWriter Not Available");
		ArrayList<String> output = new ArrayList<String>();
		KaggleImporter k = new KaggleImporter("hello", "hey");
		output = k.process(input);
		assertEquals(1, output.size());
	}
	
	/**
	 * Creates an ArrayList<String> and tests if the process in the Normalizer Class 
	 * returns the normalized ArrayList<String>
	 */
	@Test
	void testNormalizerProcess() {
		ArrayList<String> input = new ArrayList<String>();
		input.add("release year\ttitle\truntime\tsource");
		input.add("2008	The Mummy: Tomb of the Dragon Emperor	112 minutes	kaggle");
		ArrayList<String> output = new ArrayList<String>();
		ValidatorKaggle k = new ValidatorKaggle("hello", "hey");
		output = k.process(input);
		assertEquals("2008	the mummy: tomb of the dragon emperor	112	kaggle", output.get(1));
	}
	
	/**
	 * Creates an ArrayList<String> and tests adding and removing elements from an ArrayList<String>
	 * works properly by comparing it it's size.
	 */
	@Test
	void testNormalizerCorrectAmountOfAddedLines() {
		ArrayList<String> input = new ArrayList<String>();
		input.add("release year\ttitle\truntime\tsource");
		input.add("2008	The Mummy: Tomb of the Dragon Emperor	112 minutes	kaggle");
		input.add("2008	The Mummy: Tomb of the Dragon Emperor	112 minutes	kaggle");
		input.add("2008	The Mummy: Tomb of the Dragon Emperor	112 minutes	kaggle");
		input.add("2008	The Mummy: Tomb of the Dragon Emperor	112 minutes	kaggle");
		ArrayList<String> output = new ArrayList<String>();
		ValidatorKaggle k = new ValidatorKaggle("hello", "hey");
		output = k.process(input);
		assertEquals(5, output.size());
		input.add("2008	The Mummy: Tomb of the Dragon Emperor	112 minutes	kaggle");
		input.add("2008	The Mummy: Tomb of the Dragon Emperor	112 minutes	kaggle");
		output = k.process(input);
		assertEquals(7, output.size());
		input.remove(6);
		output = k.process(input);
		assertEquals(6, output.size());
	}
}
